# Generated by Django 5.2.9 on 2025-12-27 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='maintenance_interval_days',
            field=models.IntegerField(blank=True, help_text='Number of days between preventive maintenance cycles (e.g., 30 for monthly, 90 for quarterly)', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='estimated_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated duration in hours (typically set for preventive maintenance)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
